main.plugins.agev2.enabled = False
main.plugins.agev2.age_x_coord = 0
main.plugins.agev2.age_y_coord = 56
main.plugins.agev2.str_x_coord = 125
main.plugins.agev2.str_y_coord = 56
main.plugins.agev2.ap_x_coord = 0
main.plugins.agev2.ap_y_coord = 60
main.plugins.agev2.deauth_x_coord = 0
main.plugins.agev2.deauth_y_coord = 70